LOAD DATA
INFILE 'ibs_stage.csv'
REPLACE INTO TABLE ibs_stage
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
tkr       CHAR NULLIF (tkr=BLANKS)
,epochsec DECIMAL EXTERNAL NULLIF (epochsec=BLANKS)
,clse     DECIMAL EXTERNAL NULLIF (clse=BLANKS)
)
