LOAD DATA
INFILE 'ibf_stage.csv'
REPLACE INTO TABLE ibf_stage
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
pair  CHAR NULLIF (pair=BLANKS)
,epochsec   DECIMAL EXTERNAL NULLIF (epochsec=BLANKS)
,clse       DECIMAL EXTERNAL NULLIF (clse=BLANKS)
)
