LOAD DATA
INFILE 'fxw_stage.csv'
REPLACE INTO TABLE fxw_stage
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
ydate DATE "DD-Mon-RR" NULLIF (ydate=BLANKS)
,clse DECIMAL EXTERNAL NULLIF (clse=BLANKS)
,pair CHAR NULLIF (pair=BLANKS)
)

