#!/bin/bash

. /pt/s/rluck/svmspy/.orcl
. /pt/s/rluck/svmspy/.jruby

set -x

date

cd $SVMSPY

./dl_then_svm.bash  IBM
./dl_then_svm.bash  IOC
./dl_then_svm.bash  IWM
./dl_then_svm.bash  JNJ
./dl_then_svm.bash  JOYG
./dl_then_svm.bash  JPM
./dl_then_svm.bash  JWN
./dl_then_svm.bash  KO
./dl_then_svm.bash  LFT
./dl_then_svm.bash  LMT
./dl_then_svm.bash  LVS
./dl_then_svm.bash  MAR
./dl_then_svm.bash  MCD
./dl_then_svm.bash  MDT
./dl_then_svm.bash  MDY
./dl_then_svm.bash  MEE
./dl_then_svm.bash  MET
./dl_then_svm.bash  MJN
./dl_then_svm.bash  MMM
./dl_then_svm.bash  MON
./dl_then_svm.bash  MOS
./dl_then_svm.bash  MRK
./dl_then_svm.bash  MSFT
./dl_then_svm.bash  MT
./dl_then_svm.bash  MVG
./dl_then_svm.bash  NEM
./dl_then_svm.bash  NFLX
./dl_then_svm.bash  NOC
./dl_then_svm.bash  NUE
./dl_then_svm.bash  OIH
./dl_then_svm.bash  ORCL
./dl_then_svm.bash  OXY
./dl_then_svm.bash  PAAS
./dl_then_svm.bash  PALL
./dl_then_svm.bash  PBR
./dl_then_svm.bash  PEP
./dl_then_svm.bash  PG
./dl_then_svm.bash  PM
./dl_then_svm.bash  PNC
./dl_then_svm.bash  POT
./dl_then_svm.bash  PPLT
./dl_then_svm.bash  PRU
./dl_then_svm.bash  QCOM
./dl_then_svm.bash  QQQ
./dl_then_svm.bash  RDY
./dl_then_svm.bash  RIG
./dl_then_svm.bash  RIMM
./dl_then_svm.bash  RTN
./dl_then_svm.bash  SCCO
./dl_then_svm.bash  SINA
./dl_then_svm.bash  SJM
./dl_then_svm.bash  SKX
./dl_then_svm.bash  SLB
./dl_then_svm.bash  SLV
./dl_then_svm.bash  SLW
./dl_then_svm.bash  SNDK
./dl_then_svm.bash  SOHU
./dl_then_svm.bash  SPY
./dl_then_svm.bash  STT
./dl_then_svm.bash  SU
./dl_then_svm.bash  SUN
./dl_then_svm.bash  SVM
./dl_then_svm.bash  SWC
./dl_then_svm.bash  T
./dl_then_svm.bash  TEVA
./dl_then_svm.bash  TGT
./dl_then_svm.bash  TKR
./dl_then_svm.bash  TLT
./dl_then_svm.bash  TSO
./dl_then_svm.bash  TXN
./dl_then_svm.bash  UNH
./dl_then_svm.bash  UNP
./dl_then_svm.bash  UPS
./dl_then_svm.bash  V
./dl_then_svm.bash  VALE
./dl_then_svm.bash  VECO
./dl_then_svm.bash  VLO
./dl_then_svm.bash  VMW
./dl_then_svm.bash  WDC
./dl_then_svm.bash  WFC
./dl_then_svm.bash  WFMI
./dl_then_svm.bash  WHR
./dl_then_svm.bash  WMT
./dl_then_svm.bash  WYNN
./dl_then_svm.bash  X
./dl_then_svm.bash  XLB
./dl_then_svm.bash  XLE
./dl_then_svm.bash  XLU
./dl_then_svm.bash  XOM
./dl_then_svm.bash  YUM
