#!/bin/bash

. /pt/s/rluck/svmspy/.orcl
. /pt/s/rluck/svmspy/.jruby

set -x

date

cd $SVMSPY

./dl_then_svm.bash  AAPL
./dl_then_svm.bash  ABT
./dl_then_svm.bash  ABX
./dl_then_svm.bash  ADBE
./dl_then_svm.bash  AEM
./dl_then_svm.bash  AFL
./dl_then_svm.bash  AGU
./dl_then_svm.bash  AIG
./dl_then_svm.bash  AKAM
./dl_then_svm.bash  ALL
./dl_then_svm.bash  AMGN
./dl_then_svm.bash  AMT
./dl_then_svm.bash  AMX
./dl_then_svm.bash  AMZN
./dl_then_svm.bash  APA
./dl_then_svm.bash  APC
./dl_then_svm.bash  ARG
./dl_then_svm.bash  AXP
./dl_then_svm.bash  AXU
./dl_then_svm.bash  BA
./dl_then_svm.bash  BBT
./dl_then_svm.bash  BBY
./dl_then_svm.bash  BEN
./dl_then_svm.bash  BHP
./dl_then_svm.bash  BIDU
./dl_then_svm.bash  BP
./dl_then_svm.bash  BRCM
./dl_then_svm.bash  BTU
./dl_then_svm.bash  BUCY
./dl_then_svm.bash  CAT
./dl_then_svm.bash  CDE
./dl_then_svm.bash  CELG
./dl_then_svm.bash  CEO
./dl_then_svm.bash  CHK
./dl_then_svm.bash  CLF
./dl_then_svm.bash  CMI
./dl_then_svm.bash  COF
./dl_then_svm.bash  COP
./dl_then_svm.bash  COST
./dl_then_svm.bash  CREE
./dl_then_svm.bash  CRM
./dl_then_svm.bash  CSX
./dl_then_svm.bash  CTSH
./dl_then_svm.bash  CVE
./dl_then_svm.bash  CVS
./dl_then_svm.bash  CVX
./dl_then_svm.bash  DD
./dl_then_svm.bash  DE
./dl_then_svm.bash  DIA
./dl_then_svm.bash  DIS
./dl_then_svm.bash  DNDN
./dl_then_svm.bash  DTV
./dl_then_svm.bash  DVN
./dl_then_svm.bash  EBAY
./dl_then_svm.bash  EFA
./dl_then_svm.bash  EOG
./dl_then_svm.bash  ESRX
./dl_then_svm.bash  EWZ
./dl_then_svm.bash  EXK
./dl_then_svm.bash  FCX
./dl_then_svm.bash  FDX
./dl_then_svm.bash  FFIV
./dl_then_svm.bash  FLS
./dl_then_svm.bash  FSLR
./dl_then_svm.bash  FXI
./dl_then_svm.bash  GD
./dl_then_svm.bash  GDX
./dl_then_svm.bash  GFI
./dl_then_svm.bash  GG
./dl_then_svm.bash  GILD
./dl_then_svm.bash  GLD
./dl_then_svm.bash  GOOG
./dl_then_svm.bash  GS
./dl_then_svm.bash  HAL
./dl_then_svm.bash  HD
./dl_then_svm.bash  HES
./dl_then_svm.bash  HL
./dl_then_svm.bash  HOC
./dl_then_svm.bash  HON
./dl_then_svm.bash  HPQ
