#!/bin/bash

set -x

date

# The tkrs below are sorted randomly on purpose:

./svmtkr.bash  PEP
./svmtkr.bash  CTSH
./svmtkr.bash  STT
./svmtkr.bash  WYNN
./svmtkr.bash  IWM
./svmtkr.bash  AMGN
./svmtkr.bash  AFL
./svmtkr.bash  SINA
./svmtkr.bash  PBR
./svmtkr.bash  XLU
./svmtkr.bash  ABX
./svmtkr.bash  VMW
./svmtkr.bash  JWN
./svmtkr.bash  RIMM
./svmtkr.bash  IBM
./svmtkr.bash  SPY
./svmtkr.bash  CLF
./svmtkr.bash  AMX
./svmtkr.bash  SNDK
./svmtkr.bash  DD
./svmtkr.bash  TLT
./svmtkr.bash  CRM
./svmtkr.bash  LFT
./svmtkr.bash  UPS
./svmtkr.bash  FLS
./svmtkr.bash  TGT
./svmtkr.bash  AMZN
./svmtkr.bash  MET
./svmtkr.bash  PM
./svmtkr.bash  BHP
./svmtkr.bash  FCX
./svmtkr.bash  SLV
./svmtkr.bash  SJM
./svmtkr.bash  OXY
./svmtkr.bash  MT
./svmtkr.bash  JNJ
./svmtkr.bash  GG
./svmtkr.bash  AAPL
./svmtkr.bash  BBY
./svmtkr.bash  MDT
./svmtkr.bash  SUN
./svmtkr.bash  AMT
./svmtkr.bash  CREE
./svmtkr.bash  MAR
./svmtkr.bash  MOS
./svmtkr.bash  X
./svmtkr.bash  NUE
./svmtkr.bash  GS
./svmtkr.bash  EWZ
./svmtkr.bash  UNP
./svmtkr.bash  EFA
./svmtkr.bash  ESRX
./svmtkr.bash  ADBE
./svmtkr.bash  KO
./svmtkr.bash  GILD
./svmtkr.bash  ALL
./svmtkr.bash  ABT
./svmtkr.bash  CVX
./svmtkr.bash  AEM
./svmtkr.bash  OIH
./svmtkr.bash  FFIV
./svmtkr.bash  XLE
./svmtkr.bash  ARG
./svmtkr.bash  HON
./svmtkr.bash  DVN
./svmtkr.bash  DIS
./svmtkr.bash  VECO
./svmtkr.bash  V
./svmtkr.bash  RIG
./svmtkr.bash  PRU
./svmtkr.bash  NFLX
./svmtkr.bash  CVS
./svmtkr.bash  UNH
./svmtkr.bash  BEN
./svmtkr.bash  BRCM
./svmtkr.bash  PG
./svmtkr.bash  TKR
./svmtkr.bash  NEM
./svmtkr.bash  PNC
./svmtkr.bash  XOM
./svmtkr.bash  BA
./svmtkr.bash  SKX
./svmtkr.bash  APC
./svmtkr.bash  DNDN
./svmtkr.bash  BUCY
./svmtkr.bash  WMT
./svmtkr.bash  COST
./svmtkr.bash  BBT
./svmtkr.bash  CMI
./svmtkr.bash  MEE
./svmtkr.bash  BIDU
./svmtkr.bash  MJN
./svmtkr.bash  MDY
./svmtkr.bash  HES
./svmtkr.bash  DE
./svmtkr.bash  HPQ
./svmtkr.bash  APA
./svmtkr.bash  BTU
./svmtkr.bash  POT
./svmtkr.bash  GOOG
./svmtkr.bash  HD
./svmtkr.bash  JOYG
./svmtkr.bash  WHR
./svmtkr.bash  CELG
./svmtkr.bash  AXP
./svmtkr.bash  MCD
./svmtkr.bash  DIA
./svmtkr.bash  WDC
./svmtkr.bash  EOG
./svmtkr.bash  AKAM
./svmtkr.bash  COF
./svmtkr.bash  QQQQ
./svmtkr.bash  WFMI
./svmtkr.bash  FSLR
./svmtkr.bash  GDX
./svmtkr.bash  MRK
./svmtkr.bash  XLB
./svmtkr.bash  QCOM
./svmtkr.bash  BP
./svmtkr.bash  CSX
./svmtkr.bash  MON
./svmtkr.bash  TEVA
./svmtkr.bash  MMM
./svmtkr.bash  CAT
./svmtkr.bash  GLD
./svmtkr.bash  COP
./svmtkr.bash  DTV
./svmtkr.bash  AIG
./svmtkr.bash  FDX
./svmtkr.bash  IOC
./svmtkr.bash  SLB
./svmtkr.bash  JPM
