#!/bin/bash

. /pt/s/rluck/svmspy/.orcl
. /pt/s/rluck/svmspy/.jruby

set -x

date

cd $SVMSPY

./svmtkr.bash YUM
./svmtkr.bash XOM
./svmtkr.bash XLU
./svmtkr.bash XLE
./svmtkr.bash XLB
./svmtkr.bash X
./svmtkr.bash WYNN
./svmtkr.bash WMT
./svmtkr.bash WHR
./svmtkr.bash WFMI
./svmtkr.bash WFC
./svmtkr.bash WDC
./svmtkr.bash VMW
./svmtkr.bash VLO
./svmtkr.bash VECO
./svmtkr.bash VALE
./svmtkr.bash V
./svmtkr.bash UPS
./svmtkr.bash UNP
./svmtkr.bash UNH
./svmtkr.bash TXN
./svmtkr.bash TSO
./svmtkr.bash TLT
./svmtkr.bash TKR
./svmtkr.bash TGT
./svmtkr.bash TEVA
./svmtkr.bash T
./svmtkr.bash SWC
./svmtkr.bash SVM
./svmtkr.bash SUN
./svmtkr.bash SU
./svmtkr.bash STT
./svmtkr.bash SPY
./svmtkr.bash SOHU
./svmtkr.bash SNDK
./svmtkr.bash SLW
./svmtkr.bash SLV
./svmtkr.bash SLB
./svmtkr.bash SKX
./svmtkr.bash SJM
./svmtkr.bash SINA
./svmtkr.bash SCCO
./svmtkr.bash RTN
./svmtkr.bash RIMM
./svmtkr.bash RIG
./svmtkr.bash RDY
./svmtkr.bash QQQ
./svmtkr.bash QCOM
./svmtkr.bash PRU
./svmtkr.bash PPLT
./svmtkr.bash POT
./svmtkr.bash PNC
./svmtkr.bash PM
./svmtkr.bash PG
./svmtkr.bash PEP
./svmtkr.bash PBR
./svmtkr.bash PALL
./svmtkr.bash PAAS
./svmtkr.bash OXY
./svmtkr.bash ORCL
./svmtkr.bash OIH
./svmtkr.bash NUE
./svmtkr.bash NOC
./svmtkr.bash NFLX
./svmtkr.bash NEM
./svmtkr.bash MVG
./svmtkr.bash MT
./svmtkr.bash MSFT
./svmtkr.bash MRK
./svmtkr.bash MOS
./svmtkr.bash MON
./svmtkr.bash MMM
./svmtkr.bash MJN
./svmtkr.bash MET
./svmtkr.bash MEE
./svmtkr.bash MDY
./svmtkr.bash MDT
./svmtkr.bash MCD
./svmtkr.bash MAR
./svmtkr.bash LVS
./svmtkr.bash LMT
./svmtkr.bash LFT
./svmtkr.bash KO
./svmtkr.bash JWN
./svmtkr.bash JPM
./svmtkr.bash JOYG
./svmtkr.bash JNJ
./svmtkr.bash IWM
./svmtkr.bash IOC
./svmtkr.bash IBM

