LOAD DATA
INFILE 'hstage.csv'
REPLACE INTO TABLE hstage
FIELDS TERMINATED BY ';'
TRAILING NULLCOLS
(
ydate  CHAR NULLIF (ydate=BLANKS)
,ttime CHAR NULLIF (ttime=BLANKS)
,vol   DECIMAL EXTERNAL NULLIF (vol=BLANKS)
,opn   DECIMAL EXTERNAL NULLIF (opn=BLANKS)
,clse  DECIMAL EXTERNAL NULLIF (clse=BLANKS)
,mn    DECIMAL EXTERNAL NULLIF (mn=BLANKS)
,mx    DECIMAL EXTERNAL NULLIF (mx=BLANKS)
)
