# Gemfile
# After I vi Gemfile,
# remember to run shell command: bundle install --binstubs

source 'http://rubygems.org'

gem 'rake','0.8.7'

gem 'ruby-debug19', :require => 'ruby-debug'

gem 'rspec','2.5.0'



