#!/bin/bash

# many_svmtkr.bash

cd /pt/s/rluck/svmd/

set -x

./svmtkr.bash SWC
./svmtkr.bash AAPL
./svmtkr.bash ABT
./svmtkr.bash ABX
./svmtkr.bash ADBE
./svmtkr.bash AEM
./svmtkr.bash AFL
./svmtkr.bash AIG
./svmtkr.bash AKAM
./svmtkr.bash ALL
./svmtkr.bash AMGN
./svmtkr.bash AMT
./svmtkr.bash AMX
./svmtkr.bash AMZN
./svmtkr.bash APA
./svmtkr.bash APC
./svmtkr.bash ARG
./svmtkr.bash AXP
./svmtkr.bash BA
./svmtkr.bash BBT
./svmtkr.bash BBY
./svmtkr.bash BEN
./svmtkr.bash BHP
./svmtkr.bash BIDU
./svmtkr.bash BP
./svmtkr.bash BRCM
./svmtkr.bash BTU
./svmtkr.bash BUCY
./svmtkr.bash CAT
./svmtkr.bash CELG
./svmtkr.bash CLF
./svmtkr.bash CMI
./svmtkr.bash COF
./svmtkr.bash COP
./svmtkr.bash COST
./svmtkr.bash CREE
./svmtkr.bash CRM
./svmtkr.bash CSX
./svmtkr.bash CTSH
./svmtkr.bash CVS
./svmtkr.bash CVX
./svmtkr.bash DD
./svmtkr.bash DE
./svmtkr.bash DIA
./svmtkr.bash DIS
./svmtkr.bash DNDN
./svmtkr.bash DTV
./svmtkr.bash DVN
./svmtkr.bash EFA
./svmtkr.bash EOG
./svmtkr.bash ESRX
./svmtkr.bash EWZ
./svmtkr.bash FCX
./svmtkr.bash FDX
./svmtkr.bash FFIV
./svmtkr.bash FLS
./svmtkr.bash FSLR
./svmtkr.bash GDX
./svmtkr.bash GG
./svmtkr.bash GILD
./svmtkr.bash GLD
./svmtkr.bash GOOG
./svmtkr.bash GS
./svmtkr.bash HD
./svmtkr.bash HES
./svmtkr.bash HON
./svmtkr.bash HPQ
./svmtkr.bash IBM
./svmtkr.bash IOC
./svmtkr.bash IWM
./svmtkr.bash JNJ
./svmtkr.bash JOYG
./svmtkr.bash JPM
./svmtkr.bash JWN
./svmtkr.bash KO
./svmtkr.bash LFT
./svmtkr.bash MAR
./svmtkr.bash MCD
./svmtkr.bash MDT
./svmtkr.bash MDY
./svmtkr.bash MEE
./svmtkr.bash MET
./svmtkr.bash MJN
./svmtkr.bash MMM
./svmtkr.bash MON
./svmtkr.bash MOS
./svmtkr.bash MRK
./svmtkr.bash MT
./svmtkr.bash NEM
./svmtkr.bash NFLX
./svmtkr.bash NUE
./svmtkr.bash OIH
./svmtkr.bash OXY
./svmtkr.bash PBR
./svmtkr.bash PEP
./svmtkr.bash PG
./svmtkr.bash PM
./svmtkr.bash PNC
./svmtkr.bash POT
./svmtkr.bash PRU
./svmtkr.bash QCOM
./svmtkr.bash QQQQ
./svmtkr.bash RIG
./svmtkr.bash RIMM
./svmtkr.bash SINA
./svmtkr.bash SJM
./svmtkr.bash SKX
./svmtkr.bash SLB
./svmtkr.bash SLV
./svmtkr.bash SNDK
./svmtkr.bash SPY
./svmtkr.bash STT
./svmtkr.bash SUN
./svmtkr.bash TEVA
./svmtkr.bash TGT
./svmtkr.bash TKR
./svmtkr.bash TLT
./svmtkr.bash UNH
./svmtkr.bash UNP
./svmtkr.bash UPS
./svmtkr.bash V
./svmtkr.bash VECO
./svmtkr.bash VMW
./svmtkr.bash WDC
./svmtkr.bash WFMI
./svmtkr.bash WHR
./svmtkr.bash WMT
./svmtkr.bash WYNN
./svmtkr.bash X
./svmtkr.bash XLB
./svmtkr.bash XLE
./svmtkr.bash XLU
./svmtkr.bash XOM
