LOAD DATA
INFILE 'ystk_stage.csv'
replace INTO TABLE ystk_stage
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
tkr    CHAR             NULLIF (tkr=BLANKS)
,ydate DATE "YYYY-MM-DD" NULLIF (ydate=BLANKS)
,opn   DECIMAL EXTERNAL NULLIF (opn=BLANKS)
,mx    DECIMAL EXTERNAL NULLIF (mx=BLANKS)
,mn    DECIMAL EXTERNAL NULLIF (mn=BLANKS)
,clse0 DECIMAL EXTERNAL NULLIF (clse0=BLANKS)
,vol   DECIMAL EXTERNAL NULLIF (vol=BLANKS)
,clse  DECIMAL EXTERNAL NULLIF (clse=BLANKS)
)
